var geeks = [
	{
		"nom": "antoine",
		"prenom": "philippe",
		"email": "phil.antoine@gmail.com",
		"ville": "paris",
		"like1": "html5",
		"like2": "javascript",
		"like3": "barcamps",
		"hate1": "passwords",
		"hate2": "configs xml"
	},
	{
		"nom": "ardhuin",
		"prenom": "alexandre",
		"email": "alexandre.ardhuin@gmail.com",
		"ville": "nancy",
		"like1": "coder",
		"like2": "java",
		"like3": "web",
		"hate1": "ie",
		"hate2": "le code pourri"
	},
	{
		"nom": "baligand",
		"prenom": "fabien",
		"email": "fbaligand@gmail.com",
		"ville": "palaiseau",
		"like1": "java",
		"like2": "web",
		"like3": "jquery",
		"hate1": "le code illisible et inmaintenable",
		"hate2": "liferay"
	},
	{
		"nom": "bernard",
		"prenom": "emmanuel",
		"email": "emmanuel@lescastcodeurs.com",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "biville",
		"prenom": "florent",
		"email": "florent.biville@gmail.com",
		"ville": "paris",
		"like1": "apprendre",
		"like2": "java",
		"like3": "js",
		"hate1": "deprecated stuff",
		"hate2": "so-called opinionated people"
	},
	{
		"nom": "bonnel",
		"prenom": "yan",
		"email": "ybonnel@gmail.com",
		"ville": "rouen",
		"like1": "java (sous intellij)",
		"like2": "android",
		"like3": "coder avec d'autres languages (actuellement scala)",
		"hate1": "la complexité pour rien",
		"hate2": "le temps normand (je veux retourner dans le sud...)"
	},
	{
		"nom": "bonvillain",
		"prenom": "damien",
		"email": "night.kame@gmail.com",
		"ville": "montoire sur le loir",
		"like1": "coder",
		"like2": "prendre du recul",
		"like3": "java",
		"hate1": "les amnésiques",
		"hate2": "maven"
	},
	{
		"nom": "bourdon",
		"prenom": "ugo",
		"email": "bourdon.ugo@gmail.com",
		"ville": "paris",
		"like1": "scala",
		"like2": "extreme programming",
		"like3": "git",
		"hate1": "le code compliqué (différent de complexe)",
		"hate2": "faire toujours la mãªme chose"
	},
	{
		"nom": "broca",
		"prenom": "didier",
		"email": "didier.broca@libertysurf.fr",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "cazaux",
		"prenom": "jean-baptiste",
		"email": "jbcazaux@gmail.com",
		"ville": "ermont",
		"like1": "play tennis",
		"like2": "eat",
		"like3": "video games",
		"hate1": "no time for...",
		"hate2": "to lose"
	},
	{
		"nom": "chammah",
		"prenom": "tarek",
		"email": "tchammah@google.com",
		"ville": "paris",
		"like1": "ocaml",
		"like2": "dependent types",
		"like3": "hindley-milner",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "cheype",
		"prenom": "julien",
		"email": "cheype@gmail.com",
		"ville": "paris",
		"like1": "java",
		"like2": "les lapins",
		"like3": "scala",
		"hate1": "eclipse rcp",
		"hate2": "perdre mon temps"
	},
	{
		"nom": "courtine",
		"prenom": "benoit",
		"email": "benoit.courtine@gmail.com",
		"ville": "paris",
		"like1": "java (avec son indispensable intellij)",
		"like2": "linux (et plus généralement l'oss)",
		"like3": "git",
		"hate1": "les réunions inutiles (et chronophages)",
		"hate2": "les évolutions \"\"urgentes\"\" et importantes ã  faire sur un code sans tests"
	},
	{
		"nom": "david",
		"prenom": "michel",
		"email": "mimah35@gmail.com",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "de loof",
		"prenom": "nicolas",
		"email": "nicolas.deloof@gmail.com",
		"ville": "rennes",
		"like1": "coder en java (sous idea) avec mon chat sur les genoux et une bonne biã¨re",
		"like2": "git",
		"like3": "maven (si si)",
		"hate1": "devoir assurer la compatibilité ascendant sur du code legacy (ah, jenkins...)",
		"hate2": "maven (si si)"
	},
	{
		"nom": "de morlhon",
		"prenom": "jean-laurent",
		"email": "jeanlaurent@morlhon.net",
		"ville": "houilles",
		"like1": "coffeescript",
		"like2": "clean coding",
		"like3": "hacking stuff",
		"hate1": "meetings",
		"hate2": "scala"
	},
	{
		"nom": "detante",
		"prenom": "antoine",
		"email": "antoine.detante@gmail.com",
		"ville": "metz",
		"like1": "scala",
		"like2": "mac os x",
		"like3": "biã¨re",
		"hate1": "grippe",
		"hate2": "websphere"
	},
	{
		"nom": "dhordain",
		"prenom": "gautier",
		"email": "g.dhordain@gmail.com",
		"ville": "lille",
		"like1": "java",
		"like2": "apprendre des trucs utiles",
		"like3": "apprendre des trucs inutiles",
		"hate1": "grippe",
		"hate2": "code non indenté"
	},
	{
		"nom": "dumont",
		"prenom": "antoine",
		"email": "eniotna.t@gmail.com",
		"ville": "livry gargan",
		"like1": "clojure/haskell (functional prog)",
		"like2": "linux/unix",
		"like3": "simplicity",
		"hate1": "transports en commun",
		"hate2": "closed source"
	},
	{
		"nom": "finance",
		"prenom": "cédric",
		"email": "cedric.finance@soat.fr",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "gageot",
		"prenom": "david",
		"email": "david@gageot.net",
		"ville": "paris",
		"like1": "java",
		"like2": "tests",
		"like3": "chats",
		"hate1": "duplication",
		"hate2": "usines à gaz"
	},
	{
		"nom": "guérin",
		"prenom": "thomas",
		"email": "tguerin@xebia.fr",
		"ville": "paris",
		"like1": "java",
		"like2": "android",
		"like3": "scala",
		"hate1": "rer a",
		"hate2": "tu de 4000 lignes"
	},
	{
		"nom": "hanin",
		"prenom": "xavier",
		"email": "xavier.hanin@gmail.com",
		"ville": "bordeaux",
		"like1": "developpement",
		"like2": "java",
		"like3": "web",
		"hate1": "perdre du temps",
		"hate2": "le closed source"
	},
	{
		"nom": "labaye",
		"prenom": "denis",
		"email": "denis.labaye@gmail.com",
		"ville": "paris",
		"like1": "simplicity",
		"like2": "clojure, emacs",
		"like3": "mindfulness meditation",
		"hate1": "complexity",
		"hate2": "to hate"
	},
	{
		"nom": "labouisse",
		"prenom": "christophe",
		"email": "consulting@labouisse.com",
		"ville": "bordeaux",
		"like1": "java",
		"like2": "linux/unix",
		"like3": "git",
		"hate1": "qui veut épouser mon fils",
		"hate2": "récupérer du code qui \"\"marche presque\"\""
	},
	{
		"nom": "lacôte",
		"prenom": "cyril",
		"email": "cyril@ninja-squad.com",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "lagarde",
		"prenom": "jérémie",
		"email": "jeremie.codestory@gmail.com",
		"ville": "paris",
		"like1": "meet people",
		"like2": "get feedback",
		"like3": "open discussion",
		"hate1": "lose patience",
		"hate2": "rain"
	},
	{
		"nom": "le merdy",
		"prenom": "eric",
		"email": "eric.lemerdy@gmail.com",
		"ville": "suresnes",
		"like1": "java",
		"like2": "code",
		"like3": "raspberrypi",
		"hate1": "haters",
		"hate2": "untested code"
	},
	{
		"nom": "le merdy",
		"prenom": "sebastian",
		"email": "sebastian.lemerdy@gmail.com",
		"ville": "colombes",
		"like1": "java",
		"like2": "software craftsmanship",
		"like3": "smart ui",
		"hate1": "architecture",
		"hate2": ""
	},
	{
		"nom": "leclaire",
		"prenom": "mathieu",
		"email": "mat.leclaire@gmail.com",
		"ville": "metz",
		"like1": "chat",
		"like2": "linux",
		"like3": "java",
		"hate1": "le poussin piou",
		"hate2": "flex"
	},
	{
		"nom": "lemée",
		"prenom": "mathilde",
		"email": "mathilde.lemee.pmu@gmail.com",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "lemée",
		"prenom": "jean-baptiste",
		"email": "jblemee@gmail.com",
		"ville": "pontarmé",
		"like1": "clean code",
		"like2": "big data",
		"like3": "demain",
		"hate1": "les embouteillages",
		"hate2": "attendre"
	},
	{
		"nom": "lerman",
		"prenom": "benjamin",
		"email": "benjamin.lerman@google.com",
		"ville": "paris",
		"like1": "scala",
		"like2": "un defi interessant",
		"like3": "vi",
		"hate1": "xcode",
		"hate2": "perdre mon temps"
	},
	{
		"nom": "lussiez",
		"prenom": "jeremie",
		"email": "jeremie.lussiez@gmail.com",
		"ville": "seclin",
		"like1": "inventer des trucs",
		"like2": "les robots",
		"like3": "les chats",
		"hate1": "le code \"\"legacy driven\"\"",
		"hate2": "le manque de curiosité"
	},
	{
		"nom": "mandrikov",
		"prenom": "evgeny",
		"email": "mandrikov@gmail.com",
		"ville": "la roche-sur-foron",
		"like1": "codestory",
		"like2": "sonarsource",
		"like3": "linux/java/git/maven",
		"hate1": "7 deadly sins of developer",
		"hate2": "slow builds"
	},
	{
		"nom": "martignole",
		"prenom": "nicolas",
		"email": "nicolas@martignole.net",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "moulou",
		"prenom": "mouhcine",
		"email": "mouhcine.moulou@soat.fr",
		"ville": "vitry/seine",
		"like1": "java & scala",
		"like2": "video games",
		"like3": "intellij",
		"hate1": "microsoft products",
		"hate2": "java (jdk 8)"
	},
	{
		"nom": "muller",
		"prenom": "alain",
		"email": "alain.muller@gmail.com",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "neveu",
		"prenom": "audrey",
		"email": "neveu.audrey@gmail.com",
		"ville": "paris",
		"like1": "java & js",
		"like2": "linux",
		"like3": "git",
		"hate1": "me battre contre des moulins ã  vents",
		"hate2": "ceux qui savent tout mieux que tout le monde"
	},
	{
		"nom": "nizet",
		"prenom": "jean-baptiste",
		"email": "jb+codestory@ninja-squad.com",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "nopre",
		"prenom": "xavier",
		"email": "xnopre@gmail.com",
		"ville": "gap",
		"like1": "java, js, web2",
		"like2": "clean code",
		"like3": "découvrir",
		"hate1": "legacy",
		"hate2": "code pourri"
	},
	{
		"nom": "peru",
		"prenom": "nicolas",
		"email": "nicolas.peru@gmail.com",
		"ville": "genã¨ve",
		"like1": "clean code",
		"like2": "jouer",
		"like3": "neige",
		"hate1": "joe les bonnes idées",
		"hate2": "overkill"
	},
	{
		"nom": "philippart",
		"prenom": "gilles",
		"email": "gilles.philippart@sgcib.com",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "renou",
		"prenom": "morgan",
		"email": "mrenou@gmail.com",
		"ville": "versailles",
		"like1": "clean code",
		"like2": "java",
		"like3": "idea",
		"hate1": "les epinards",
		"hate2": "les méthodes de 50 lignes"
	},
	{
		"nom": "rose",
		"prenom": "guillaume",
		"email": "guillaume.rose@gmail.com",
		"ville": "issy",
		"like1": "robotique",
		"like2": "logiciels libres",
		"like3": "agile",
		"hate1": "legacy",
		"hate2": "complexité inutile"
	},
	{
		"nom": "roux",
		"prenom": "julien",
		"email": "roujul@gmail.com",
		"ville": "genã¨ve",
		"like1": "moto",
		"like2": "football",
		"like3": "biã¨re",
		"hate1": "mes voisins",
		"hate2": "paris"
	},
	{
		"nom": "sirot",
		"prenom": "jean-christophe",
		"email": "jcsirot@gmail.com",
		"ville": "ivry-sur-seine",
		"like1": "coder (en java mais pas que)",
		"like2": "l'irlande",
		"like3": "les jeux video",
		"hate1": "la ratp",
		"hate2": "ceux qui pense que c'était mieux avant"
	},
	{
		"nom": "tremblay",
		"prenom": "henri",
		"email": "henri.tremblay@gmail.com",
		"ville": "paris",
		"like1": "java",
		"like2": "performance",
		"like3": "easymock",
		"hate1": "le manque de pragmatisme",
		"hate2": "tout de qui est lent"
	},
	{
		"nom": "vilbé",
		"prenom": "yves",
		"email": "uv0.xtr@gmail.com",
		"ville": "",
		"like1": "",
		"like2": "",
		"like3": "",
		"hate1": "",
		"hate2": ""
	},
	{
		"nom": "voisin",
		"prenom": "benoã®t",
		"email": "bvo123@123mail.org",
		"ville": "paris",
		"like1": "java",
		"like2": "agile",
		"like3": "scala",
		"hate1": "le rouge",
		"hate2": "ne pas s'améliorer"
	},
	{
		"nom": "wauquier",
		"prenom": "francois",
		"email": "wokier@gmail.com",
		"ville": "paris",
		"like1": "java",
		"like2": "tdd",
		"like3": "agile",
		"hate1": "duplication",
		"hate2": "le rouge"
	},
	{
		"nom": "wursteisen",
		"prenom": "david",
		"email": "david.wursteisen@gmail.com",
		"ville": "boulogne",
		"like1": "le vide",
		"like2": "photo",
		"like3": "starcraft ii",
		"hate1": "starcraft ii",
		"hate2": "la complexité inutile"
	},
	{
		"nom": "zoritchak",
		"prenom": "gaetan",
		"email": "g.zoritchak@gmail.com",
		"ville": "genã¨ve",
		"like1": "clean code",
		"like2": "kotlin",
		"like3": "intellij",
		"hate1": "xml",
		"hate2": "le code perdu dans la doc"
	},
	{
		"nom": "mitnick",
		"prenom": "kevin",
		"email": "kevin@condor.net",
		"ville": "equateur",
		"like1": "hacking",
		"like2": "vms",
		"like3": "tcp",
		"hate1": "fbi",
		"hate2": "shimomura"
	},
	{
		"nom": "torvald",
		"prenom": "linus",
		"email": "torvalds@osdl.org",
		"ville": "helsinki",
		"like1": "linux",
		"like2": "git",
		"like3": "plongée",
		"hate1": "fsf",
		"hate2": "rms"
	},
	{
		"nom": "gates",
		"prenom": "bill",
		"email": "bill@gates.org",
		"ville": "seattle",
		"like1": "windows",
		"like2": "ms-dos",
		"like3": "visual studio",
		"hate1": "blue screen",
		"hate2": "cash"
	},
	{
		"nom": "laforge",
		"prenom": "guillaume",
		"email": "glaforge@gmail.com",
		"ville": "villiers sur marne",
		"like1": "groovy",
		"like2": "grails",
		"like3": "blagues",
		"hate1": "devoxx fr",
		"hate2": "erlang"
	},
	{
		"nom": "carmack",
		"prenom": "john",
		"email": "john@doom.com",
		"ville": "roeland park",
		"like1": "doom",
		"like2": "quake",
		"like3": "3d",
		"hate1": "sprites",
		"hate2": "unreal tournament"
	},
	{
		"nom": "gosling",
		"prenom": "james",
		"email": "james@javawillneverdie.com",
		"ville": "moutainview",
		"like1": "java",
		"like2": "jvm",
		"like3": "robots",
		"hate1": "surcharge d'opérateur",
		"hate2": "oracle"
	},
	{
		"nom": "zuckerberg",
		"prenom": "mark",
		"email": "imceobitch@facebook.com",
		"ville": "palo alto",
		"like1": "facebook",
		"like2": "tongues",
		"like3": "php",
		"hate1": "tyler winklevoss",
		"hate2": "cameron winklevoss"
	},
	{
		"nom": "ordersky",
		"prenom": "martin",
		"email": "martin@scalaftw.net",
		"ville": "lausanne",
		"like1": "scala",
		"like2": "java generics",
		"like3": "javac",
		"hate1": "untyped language",
		"hate2": "scripting"
	},
	{
		"nom": "beck",
		"prenom": "kent",
		"email": "kent@tdd.org",
		"ville": "medford",
		"like1": "smalltalk",
		"like2": "junit",
		"like3": "tdd",
		"hate1": "waterfall",
		"hate2": "big design upfront"
	}
];